-- STAFF 테이블에 SeaweedFS 사진 key 컬럼 추가
ALTER TABLE HOSPITAL.STAFF ADD (
    STAFF_PHOTO_KEY VARCHAR2(200 BYTE)
);

COMMENT ON COLUMN HOSPITAL.STAFF.STAFF_PHOTO_KEY IS 'SeaweedFS 객체 key (예: a1b2c3d4.jpg)';
