-- 인코딩 깨짐으로 잘못 저장된 NAME 교정 ('진료 메인' = \C9C4\B8CC \BA54\C778)
UPDATE AUTH_MENU
SET NAME       = UNISTR('\C9C4\B8CC \BA54\C778'),
    UPDATED_AT = SYSTIMESTAMP
WHERE MENU_ID = 1301;

COMMIT;

SELECT MENU_ID, CODE, NAME FROM AUTH_MENU WHERE MENU_ID = 1301;
